import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav-bar";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const roboto = Roboto({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AntdRegistry>
          <div className="h-[9vh]">
            <Navbar />
          </div>
          <div className="flex justify-center items-center h-[91vh]">
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
